### ISSUE TITLE
install from package

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/lynis-formula#1]
It should be possible to install lynis from repo package instead of git.

**Comment by mostafahussein** [comment]
There is a discussion about this formula with [Michael Boelen](https://github.com/mboelen) on [salt-users](https://groups.google.com/forum/#!topic/salt-users/yMhV0PUlmFo) in order to decide the best approach, as we are going to integrate this formula with [this one](https://github.com/CISOfy/lynis-saltstack) to cover more cases and the package installation is one of them.

**Comment by aboe76** [comment]
@mostafahussein Nice, please ping me, when it's ready I will test it.

I have setup my own test rack, with multiple distributions for saltstack-formulas:
- debian 8/9
- opensuse leap/tumbleweed
- centos/fedora/redhat
- ubuntu
- archlinux

**Comment by aboe76** [comment]
@mostafahussein see #2

**Comment by mostafahussein** [comment]
Thanks @aboe76 !
